language: generic
sudo: required
services:
    - docker

before_install: 
    - docker build -t corb450/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true corb450/react-test npm test

after_success:
    - docker build -t corb450/multi-client ./client
    - docker build -t corb450/multi-nginx ./nginx
    - docker build -t corb450/multi-server ./server
    - docker build -t corb450/multi-worker ./worker
    # Log in to the docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push corb450/multi-client
    - docker push corb450/multi-nginx
    - docker push corb450/multi-server
    - docker push corb450/multi-worker

deploy: 
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env-1
    bucket_name: elasticbeanstalk-us-east-2-408653790911
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    edge: true
    provider: elasticbeanstalk
    ...